[package]
description = "proto"
name = "libproto"
version = "0.6.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
protobuf = { version = "^1.0.0"}
cita-crypto = { path = "../cita-crypto" }
util = { path = "../util" }
rustc-serialize = "0.3"
rlp = { path = "../rlp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
grpc = "0.2.1"
tls-api = "0.1.14"

[features]
default = []
secp256k1 = ["cita-crypto/secp256k1"]
ed25519 = ["cita-crypto/ed25519"]
sm2 = ["cita-crypto/sm2"]
sha3hash = ["util/sha3hash"]
blake2bhash = ["util/blake2bhash"]
sm3hash = ["util/sm3hash"]
